# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSSwiftUIGIFViewExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSSwiftUIGIFViewExample
  pod 'SSSwiftUIGIFView'
  
  target 'SSSwiftUIGIFViewExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SSSwiftUIGIFViewExampleUITests' do
    # Pods for testing
  end

end

target 'SSSwiftUIGIFViewExampleMacOS' do
  pod 'SSSwiftUIGIFView'
end
